


import database.Assignments;
import database.Grades;
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.awt.Image;
import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.DriverManager;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.JTableHeader;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JFrame;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class AssignmentsEvaluation extends javax.swing.JFrame {

    static int index = 0;

    /**
     * Creates new form CourseGradesProf
     * @param rs
     */
    public AssignmentsEvaluation(ResultSet rs) throws SQLException {
        initComponents();
        this.setLocationRelativeTo(null);
        jLbl_TAName.setText(""+rs.getBigDecimal("TEACHERID"));
        jLbl_TAID.setText(rs.getString("TEACHERNAME"));
        jLbl_TAEmail.setText(rs.getString("EMAIL"));
    }
    public AssignmentsEvaluation() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    //Function to make the label's background white when the mouse entered.
    public void scaleimage__backcwhite(JLabel label, String path) {
        ImageIcon icon = new ImageIcon(path);
        Image img = icon.getImage();
        Image imgscale = img.getScaledInstance(label.getWidth(), label.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgscale);
        label.setIcon(scaledIcon);
    }
    private void callTimer(JFrame notification) {
        Timer timer = new Timer();
        notification.setVisible(true);
        timer.schedule(new TimerTask() {
            @Override
            public void run() {
                notification.setVisible(false);
            }
        }, 6000);
    }
    //Function to return the label's original background when the mouse exited.
    public void scaleimage__backc_white_remove(JLabel label) {
        ImageIcon icon = new ImageIcon("");
        Image img = icon.getImage();
        Image imgscale = img.getScaledInstance(label.getWidth(), label.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgscale);
        label.setIcon(scaledIcon);
    }

    //Function to replace the button with another one with a different color.
    public void scaleimage__replaceButton(JLabel label, String path) {
        ImageIcon icon = new ImageIcon(path);
        Image img = icon.getImage();
        Image imgscale = img.getScaledInstance(label.getWidth(), label.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgscale);
        label.setIcon(scaledIcon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLbl_GradeIcon = new javax.swing.JLabel();
        jLbl_Header = new javax.swing.JLabel();
        jLbl_returnBack = new javax.swing.JLabel();
        jLbl_UpBar = new javax.swing.JLabel();
        jLbl_Name = new javax.swing.JLabel();
        jLbl_TAName = new javax.swing.JLabel();
        jLbl_ID = new javax.swing.JLabel();
        jLbl_TAID = new javax.swing.JLabel();
        jLbl_Email = new javax.swing.JLabel();
        jLbl_TAEmail = new javax.swing.JLabel();
        jLbl_Question = new javax.swing.JLabel();
        jCheckBox_Assignment1 = new javax.swing.JCheckBox();
        jCheckBox_Assignment2 = new javax.swing.JCheckBox();
        jLbl_Confirm = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(563, 440));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 252, 239));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLbl_GradeIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbl_GradeIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sprint#3Images/GradesIcon.png"))); // NOI18N
        jPanel1.add(jLbl_GradeIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 70));

        jLbl_Header.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 48)); // NOI18N
        jLbl_Header.setForeground(new java.awt.Color(255, 255, 255));
        jLbl_Header.setText("Grading System");
        jPanel1.add(jLbl_Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 8, 420, 60));

        jLbl_returnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sprint#3Images/OrangeExit.png"))); // NOI18N
        jLbl_returnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLbl_returnBackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLbl_returnBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLbl_returnBackMouseExited(evt);
            }
        });
        jPanel1.add(jLbl_returnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, 40, 40));

        jLbl_UpBar.setBackground(new java.awt.Color(38, 50, 54));
        jLbl_UpBar.setOpaque(true);
        jPanel1.add(jLbl_UpBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 70));

        jLbl_Name.setBackground(new java.awt.Color(153, 204, 255));
        jLbl_Name.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLbl_Name.setForeground(new java.awt.Color(78, 111, 207));
        jLbl_Name.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sprint#3Images/NameIcon.png"))); // NOI18N
        jLbl_Name.setText("Teacher's Name:");
        jPanel1.add(jLbl_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 150, 40));

        jLbl_TAName.setText("Israa Kamal Odeh");
        jPanel1.add(jLbl_TAName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 180, 40));

        jLbl_ID.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLbl_ID.setForeground(new java.awt.Color(78, 111, 207));
        jLbl_ID.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sprint#3Images/IDIcon.png"))); // NOI18N
        jLbl_ID.setText("Teacher ID:");
        jPanel1.add(jLbl_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 120, 40));

        jLbl_TAID.setText("11927086");
        jPanel1.add(jLbl_TAID, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 150, 180, 40));

        jLbl_Email.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLbl_Email.setForeground(new java.awt.Color(78, 111, 207));
        jLbl_Email.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sprint#3Images/Email.png"))); // NOI18N
        jLbl_Email.setText("Email:");
        jPanel1.add(jLbl_Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 70, 30));

        jLbl_TAEmail.setText("Israa.k.Odeh@gmail.com");
        jPanel1.add(jLbl_TAEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 180, 30));

        jLbl_Question.setBackground(new java.awt.Color(78, 111, 207));
        jLbl_Question.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLbl_Question.setForeground(new java.awt.Color(255, 255, 255));
        jLbl_Question.setText("        Which Assignments would you assign to this teacher assistant to evaluate?");
        jLbl_Question.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLbl_Question.setOpaque(true);
        jPanel1.add(jLbl_Question, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 570, 50));

        jCheckBox_Assignment1.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jCheckBox_Assignment1.setForeground(new java.awt.Color(78, 111, 207));
        jCheckBox_Assignment1.setText("Assignment 1");
        jPanel1.add(jCheckBox_Assignment1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 130, 30));

        jCheckBox_Assignment2.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jCheckBox_Assignment2.setForeground(new java.awt.Color(78, 111, 207));
        jCheckBox_Assignment2.setText("Assignment 2");
        jPanel1.add(jCheckBox_Assignment2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 350, 130, 30));

        jLbl_Confirm.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLbl_Confirm.setForeground(new java.awt.Color(0, 0, 0));
        jLbl_Confirm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbl_Confirm.setText("Confirm");
        jLbl_Confirm.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(98, 168, 243)));
        jLbl_Confirm.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLbl_Confirm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLbl_ConfirmMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLbl_ConfirmMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLbl_ConfirmMouseExited(evt);
            }
        });
        jPanel1.add(jLbl_Confirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, 180, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLbl_returnBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbl_returnBackMouseExited
        scaleimage__replaceButton(jLbl_returnBack, "src\\photo\\botton\\OrangeExit.png");
    }//GEN-LAST:event_jLbl_returnBackMouseExited

    private void jLbl_returnBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbl_returnBackMouseEntered
        scaleimage__backcwhite(jLbl_returnBack, "src\\photo\\botton\\rel_exit.png");
    }//GEN-LAST:event_jLbl_returnBackMouseEntered

    private void jLbl_returnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbl_returnBackMouseClicked
        new ProfessorGradingInterface().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLbl_returnBackMouseClicked

    private void jLbl_ConfirmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbl_ConfirmMouseClicked
        // TODO add your handling code here:
        
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("Software_ProjectPU");
        EntityManager em = emf.createEntityManager();
        em.getTransaction().begin();
        Assignments assignment_to_edit = em.find(Assignments.class, new BigDecimal(ProfessorCourseSections.sel_sec));
        boolean exists = true;
        if(assignment_to_edit == null){
            exists = false;
            assignment_to_edit = new Assignments();
        }
        if(jCheckBox_Assignment1.isSelected())
            assignment_to_edit.setPermission("T");
        else
            assignment_to_edit.setPermission("F");
        if(jCheckBox_Assignment2.isSelected())
            assignment_to_edit.setPermission2("T");
        else
            assignment_to_edit.setPermission2("F");
        new ProfessorGradingInterface().setVisible(true);
        this.setVisible(false);
        if(!exists){
            assignment_to_edit.setAssignmentno(BigDecimal.valueOf(ProfessorCourseSections.sel_sec));
            em.persist(assignment_to_edit);
        }
        
        em.getTransaction().commit();
        em.close();
        callTimer(new SuccessNotification("Job Assigned successfully!"));
    }//GEN-LAST:event_jLbl_ConfirmMouseClicked

    private void jLbl_ConfirmMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbl_ConfirmMouseEntered
        // TODO add your handling code here:
        scaleimage__backcwhite(jLbl_Confirm, "src\\photo\\white.png");
        jLbl_Confirm.setForeground(new Color(98,168,243));
    }//GEN-LAST:event_jLbl_ConfirmMouseEntered

    private void jLbl_ConfirmMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbl_ConfirmMouseExited
        // TODO add your handling code here:
        scaleimage__backc_white_remove(jLbl_Confirm);
        jLbl_Confirm.setForeground(Color.black);
    }//GEN-LAST:event_jLbl_ConfirmMouseExited

   
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CourseGradesProf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CourseGradesProf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CourseGradesProf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CourseGradesProf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AssignmentsEvaluation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox_Assignment1;
    private javax.swing.JCheckBox jCheckBox_Assignment2;
    private javax.swing.JLabel jLbl_Confirm;
    private javax.swing.JLabel jLbl_Email;
    private javax.swing.JLabel jLbl_GradeIcon;
    private javax.swing.JLabel jLbl_Header;
    private javax.swing.JLabel jLbl_ID;
    private javax.swing.JLabel jLbl_Name;
    private javax.swing.JLabel jLbl_Question;
    private javax.swing.JLabel jLbl_TAEmail;
    private javax.swing.JLabel jLbl_TAID;
    private javax.swing.JLabel jLbl_TAName;
    private javax.swing.JLabel jLbl_UpBar;
    private javax.swing.JLabel jLbl_returnBack;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
