


import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.awt.Image;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.JTableHeader;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class CourseGrades1TA extends javax.swing.JFrame {


    /**
     * Creates new form CourseGrades
     */
    public CourseGrades1TA() {
        initComponents();
        jTable_Grades.getTableHeader().setDefaultRenderer(new HeaderSpecifications());
        
        jTable_Grades.setRowHeight(25);
        jScrollPane_Grades.getViewport().setBackground(new Color(253, 252, 246));
    }
    
    
    //This function is a timer that specifies the time of showing the notification, once you need
    //to display a notification, then you must pass the notification to this timer to view the
    //notification for some time then hide it.
    
    //I have created an example of what I have explained, please
    //go below to the private void jLbl_AddMouseClicked() function and see what I mean.
    private void callTimer(JFrame notification) {
        Timer timer = new Timer();
        timer.schedule(new TimerTask() {
            @Override
            public void run() {
                notification.setVisible(false);
            }
        }, 6000);
    }

    //Function to make the label's background white when the mouse entered.
    public void scaleimage__backcwhite(JLabel label, String path) {
        ImageIcon icon = new ImageIcon(path);
        Image img = icon.getImage();
        Image imgscale = img.getScaledInstance(label.getWidth(), label.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgscale);
        label.setIcon(scaledIcon);
    }
    
    //Function to return the label's original background when the mouse exited.
    public void scaleimage__backc_white_remove(JLabel label) {
        ImageIcon icon = new ImageIcon("");
        Image img = icon.getImage();
        Image imgscale = img.getScaledInstance(label.getWidth(), label.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgscale);
        label.setIcon(scaledIcon);
    }

    //Function to replace the button with another one with a different color.
    public void scaleimage__replaceButton(JLabel label, String path) {
        ImageIcon icon = new ImageIcon(path);
        Image img = icon.getImage();
        Image imgscale = img.getScaledInstance(label.getWidth(), label.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgscale);
        label.setIcon(scaledIcon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLbl_GradeIcon = new javax.swing.JLabel();
        jLbl_header = new javax.swing.JLabel();
        jLbl_SearchEye = new javax.swing.JLabel();
        jTxt_SearchID = new javax.swing.JTextField();
        jLbl_returnBack = new javax.swing.JLabel();
        jLbl_UpBar = new javax.swing.JLabel();
        jTxt_StuID = new javax.swing.JTextField();
        jTxt_Grade = new javax.swing.JTextField();
        jLbl_Add = new javax.swing.JLabel();
        jLbl_Update = new javax.swing.JLabel();
        jLbl_Remove = new javax.swing.JLabel();
        jScrollPane_Grades = new javax.swing.JScrollPane();
        jTable_Grades = new javax.swing.JTable();

        setMinimumSize(new java.awt.Dimension(1283, 694));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(253, 252, 246));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLbl_GradeIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbl_GradeIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sprint#3Images/GradesIcon.png"))); // NOI18N
        jPanel1.add(jLbl_GradeIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 70));

        jLbl_header.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 48)); // NOI18N
        jLbl_header.setForeground(new java.awt.Color(255, 255, 255));
        jLbl_header.setText("Grading System");
        jPanel1.add(jLbl_header, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 8, 420, 60));

        jLbl_SearchEye.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbl_SearchEye.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sprint#3Images/OrangeSearch.png"))); // NOI18N
        jLbl_SearchEye.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLbl_SearchEyeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLbl_SearchEyeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLbl_SearchEyeMouseExited(evt);
            }
        });
        jPanel1.add(jLbl_SearchEye, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 17, 30, 30));

        jTxt_SearchID.setBackground(new Color(255, 255, 255, 0));
        jTxt_SearchID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTxt_SearchID.setForeground(new java.awt.Color(255, 255, 255));
        jTxt_SearchID.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTxt_SearchID.setText("Enter a student's ID");
        jTxt_SearchID.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        jTxt_SearchID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTxt_SearchIDFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTxt_SearchIDFocusLost(evt);
            }
        });
        jPanel1.add(jTxt_SearchID, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 16, 310, 40));

        jLbl_returnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sprint#3Images/OrangeExit.png"))); // NOI18N
        jLbl_returnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLbl_returnBackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLbl_returnBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLbl_returnBackMouseExited(evt);
            }
        });
        jPanel1.add(jLbl_returnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 10, 40, 40));

        jLbl_UpBar.setBackground(new java.awt.Color(38, 50, 54));
        jLbl_UpBar.setOpaque(true);
        jPanel1.add(jLbl_UpBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 70));

        jTxt_StuID.setBackground(new Color(255, 255, 255, 0));
        jTxt_StuID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTxt_StuID.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTxt_StuID.setText("Type the student's ID");
        jTxt_StuID.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 102, 102)));
        jTxt_StuID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTxt_StuIDFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTxt_StuIDFocusLost(evt);
            }
        });
        jPanel1.add(jTxt_StuID, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 310, 40));

        jTxt_Grade.setBackground(new Color(255, 255, 255, 0));
        jTxt_Grade.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTxt_Grade.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTxt_Grade.setText("Type the grade");
        jTxt_Grade.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 102, 102)));
        jTxt_Grade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTxt_GradeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTxt_GradeFocusLost(evt);
            }
        });
        jPanel1.add(jTxt_Grade, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 310, 40));

        jLbl_Add.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLbl_Add.setForeground(new java.awt.Color(0, 0, 0));
        jLbl_Add.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbl_Add.setText("Add Grade");
        jLbl_Add.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(98, 168, 243)));
        jLbl_Add.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLbl_Add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLbl_AddMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLbl_AddMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLbl_AddMouseExited(evt);
            }
        });
        jPanel1.add(jLbl_Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, 180, 50));

        jLbl_Update.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLbl_Update.setForeground(new java.awt.Color(0, 0, 0));
        jLbl_Update.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbl_Update.setText("Update Grade");
        jLbl_Update.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(98, 168, 243)));
        jLbl_Update.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLbl_Update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLbl_UpdateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLbl_UpdateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLbl_UpdateMouseExited(evt);
            }
        });
        jPanel1.add(jLbl_Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 570, 180, 50));

        jLbl_Remove.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLbl_Remove.setForeground(new java.awt.Color(0, 0, 0));
        jLbl_Remove.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbl_Remove.setText("Remove Grade");
        jLbl_Remove.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(98, 168, 243)));
        jLbl_Remove.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLbl_Remove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLbl_RemoveMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLbl_RemoveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLbl_RemoveMouseExited(evt);
            }
        });
        jPanel1.add(jLbl_Remove, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 470, 180, 50));

        jTable_Grades.setBackground(new java.awt.Color(240, 240, 240));
        jTable_Grades.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jTable_Grades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "                   Student ID", "                   Student Name", "                   Assignment 1"
            }
        ));
        jTable_Grades.setGridColor(new java.awt.Color(73, 129, 189));
        jTable_Grades.setRowHeight(25);
        jTable_Grades.setSelectionBackground(new java.awt.Color(147, 194, 210));
        jTable_Grades.setShowGrid(true);
        jTable_Grades.getTableHeader().setReorderingAllowed(false);
        jScrollPane_Grades.setViewportView(jTable_Grades);

        jPanel1.add(jScrollPane_Grades, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, 800, 630));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLbl_RemoveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbl_RemoveMouseExited
        scaleimage__backc_white_remove(jLbl_Remove);
        jLbl_Remove.setForeground(Color.black);
    }//GEN-LAST:event_jLbl_RemoveMouseExited

    private void jLbl_RemoveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbl_RemoveMouseEntered
        scaleimage__backcwhite(jLbl_Remove, "src\\photo\\white.png");
        jLbl_Remove.setForeground(new Color(98, 168, 243));
    }//GEN-LAST:event_jLbl_RemoveMouseEntered

    private void jLbl_UpdateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbl_UpdateMouseExited
        scaleimage__backc_white_remove(jLbl_Update);
        jLbl_Update.setForeground(Color.black);
    }//GEN-LAST:event_jLbl_UpdateMouseExited

    private void jLbl_UpdateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbl_UpdateMouseEntered
        scaleimage__backcwhite(jLbl_Update, "src\\photo\\white.png");
        jLbl_Update.setForeground(new Color(98, 168, 243));
    }//GEN-LAST:event_jLbl_UpdateMouseEntered

    private void jLbl_AddMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbl_AddMouseExited
        scaleimage__backc_white_remove(jLbl_Add);
        jLbl_Add.setForeground(Color.black);
    }//GEN-LAST:event_jLbl_AddMouseExited

    private void jLbl_AddMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbl_AddMouseEntered
        scaleimage__backcwhite(jLbl_Add, "src\\photo\\white.png");
        jLbl_Add.setForeground(new Color(98, 168, 243));
    }//GEN-LAST:event_jLbl_AddMouseEntered

    private void jTxt_GradeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxt_GradeFocusLost
        if (jTxt_Grade.getText().equals("")) {
            jTxt_Grade.setText("Type the grade");
        }
    }//GEN-LAST:event_jTxt_GradeFocusLost

    private void jTxt_GradeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxt_GradeFocusGained
        if (jTxt_Grade.getText().equals("Type the grade")) {
            jTxt_Grade.setText("");
        }
    }//GEN-LAST:event_jTxt_GradeFocusGained

    private void jTxt_StuIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxt_StuIDFocusLost
        if (jTxt_StuID.getText().equals("")) {
            jTxt_StuID.setText("Type the student's ID");
        }
    }//GEN-LAST:event_jTxt_StuIDFocusLost

    private void jTxt_StuIDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxt_StuIDFocusGained
        if (jTxt_StuID.getText().equals("Type the student's ID")) {
            jTxt_StuID.setText("");
        }
    }//GEN-LAST:event_jTxt_StuIDFocusGained

    private void jLbl_returnBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbl_returnBackMouseExited
        scaleimage__replaceButton(jLbl_returnBack, "src\\photo\\botton\\OrangeExit.png");
    }//GEN-LAST:event_jLbl_returnBackMouseExited

    private void jLbl_returnBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbl_returnBackMouseEntered
        scaleimage__backcwhite(jLbl_returnBack, "src\\photo\\botton\\rel_exit.png");
    }//GEN-LAST:event_jLbl_returnBackMouseEntered

    private void jTxt_SearchIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxt_SearchIDFocusLost
        if (jTxt_SearchID.getText().equals("")) {
            jTxt_SearchID.setText("Enter a student's ID");
        }
    }//GEN-LAST:event_jTxt_SearchIDFocusLost

    private void jTxt_SearchIDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxt_SearchIDFocusGained
        if (jTxt_SearchID.getText().equals("Enter a student's ID")) {
            jTxt_SearchID.setText("");
        }
    }//GEN-LAST:event_jTxt_SearchIDFocusGained

    private void jLbl_SearchEyeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbl_SearchEyeMouseExited
        scaleimage__replaceButton(jLbl_SearchEye, "src\\photo\\OrangeSearch.png");

    }//GEN-LAST:event_jLbl_SearchEyeMouseExited

    private void jLbl_SearchEyeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbl_SearchEyeMouseEntered
        scaleimage__backcwhite(jLbl_SearchEye, "src\\photo\\WhiteSearch.png");
    }//GEN-LAST:event_jLbl_SearchEyeMouseEntered

    
     //Once this button is clicked, you must store the data in both the database and the jTable_Grades.
    //If the data is added, then a notification interface called "successNotification" will appear.
    //Note: You pass the following statement to the notification in case of a successful addition "The garde is successfully added!".
    
    //otherwise, a notification interface called "ErrorNotification" or "WarningNotification" will appear.
    //Note: You pass the following statement to the notification in case of an unsuccessful addition "The garde can't be added!".
    
    //Once this button is clicked, you must store the data in the database, and view the new stored data in the jTable_Grades.
    private void jLbl_AddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbl_AddMouseClicked
        // TODO add your handling code here:
        
//        //if the grade is added successfully
//        SuccessNotification successNotifiy = new SuccessNotification();
//        successNotifiy.setText("The grade is successfully added!");
//        successNotifiy.setVisible(true);
//        callTimer(successNotifiy);
        
//        //if the grade can't be added
//        ErrorNotification ErrorNotifiy = new ErrorNotification();
//        ErrorNotifiy.setText("The garde can't be added!");
//        ErrorNotifiy.setVisible(true);
//        callTimer(ErrorNotifiy);

//If you need to display some warning you could do the following

        WarningNotification WarningNotifiy = new WarningNotification();
        WarningNotifiy.setText("The garde can't be added!");
        WarningNotifiy.setVisible(true);
        callTimer(WarningNotifiy);


    }//GEN-LAST:event_jLbl_AddMouseClicked
    
    //Once this button is clicked, you must delete the data from both the database and the jTable_Grades.
    //To delete a specific grade you must search for a specific student using the search button.
    //If the data is deleted, then a notification interface called "successNotification" will appear.
    //Note: You pass the following statement to the notification in case of a successful delete "The garde is successfully deleted!".
    
    //otherwise, a notification interface called "ErrorNotification" or "WarningNotification" will appear.
    //Note: You pass the following statement to the notification in case of an unsuccessful deletion"The garde can't be deleted!".
    private void jLbl_RemoveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbl_RemoveMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLbl_RemoveMouseClicked
    
    //Once this button is clicked, you must update existing data in both the database and the jTable_Grades.
    //To update a specific grade you must search for a specific student using the search button.
    //If the data is updated, then a notification interface called "successNotification" will appear.
    //Note: You pass the following statement to the notification in case of a successful delete "The garde is successfully updated!".
    
    //otherwise, a notification interface called "ErrorNotification" or "WarningNotification" will appear.
    //Note: You pass the following statement to the notification in case of an unsuccessful deletion "The garde can't be deleted!".
    private void jLbl_UpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbl_UpdateMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLbl_UpdateMouseClicked

    //Once this button is clicked, you must search for the student with the specified ID in the jTxt_SearchID field, and fill his/her ID in 
    //jTxt_StuID field, and his/her grade in jTxt_Grade field.
    
    //If the data is found, then a notification interface called "successNotification" will appear.
    //Note: You pass the following statement to the notification in case of a successful search "The student ID is successfully found!".
    
    //otherwise, a notification interface called "ErrorNotification" or "WarningNotification" will appear.
    //Note: You pass the following statement to the notification in case of an unsuccessful search "The student ID isn't found!".
    private void jLbl_SearchEyeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbl_SearchEyeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLbl_SearchEyeMouseClicked

    //Function to return back to the main grading interface of the teacher "TeacherGradingInterface".
    private void jLbl_returnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbl_returnBackMouseClicked
        // TODO add your handling code here:
        new TeacherGradingInterface().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLbl_returnBackMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CourseGradesProf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CourseGradesProf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CourseGradesProf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CourseGradesProf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CourseGrades1TA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLbl_Add;
    private javax.swing.JLabel jLbl_GradeIcon;
    private javax.swing.JLabel jLbl_Remove;
    private javax.swing.JLabel jLbl_SearchEye;
    private javax.swing.JLabel jLbl_UpBar;
    private javax.swing.JLabel jLbl_Update;
    private javax.swing.JLabel jLbl_header;
    private javax.swing.JLabel jLbl_returnBack;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane_Grades;
    private javax.swing.JTable jTable_Grades;
    private javax.swing.JTextField jTxt_Grade;
    private javax.swing.JTextField jTxt_SearchID;
    private javax.swing.JTextField jTxt_StuID;
    // End of variables declaration//GEN-END:variables

    static public class HeaderSpecifications extends DefaultTableCellRenderer {
        public HeaderSpecifications() {
        setOpaque(true);
        }
        public Component getTableCellRendererComponent(JTable myTable, Object value, boolean selected, boolean focused, int row, int column) {
            super.getTableCellRendererComponent(myTable, value, selected, focused, row, column);
            setBackground(new Color(38,50,54));
            setFont(new Font("Segoe UI", Font.BOLD, 15));
            setForeground(Color.white);
            return this;
        }
    }
}
