


import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.JTableHeader;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class ProfessorGradingInterface extends javax.swing.JFrame {

    /**
     * Creates new form CourseGradesProf
     */
    public ProfessorGradingInterface() {
        initComponents();
    }
    
    
    //Notes about the buttons of this interface:
       
    //When Assignments Evaluation button is clicked, an AssignmentsEvaluation Interface will be opened
    //to assign a specific assignment to the teacher assistant of this section.
    

    
    
    //Function to make the label's background white when the mouse entered.
    public void scaleimage__backcwhite(JLabel label, String path) {
        ImageIcon icon = new ImageIcon(path);
        Image img = icon.getImage();
        Image imgscale = img.getScaledInstance(label.getWidth(), label.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgscale);
        label.setIcon(scaledIcon);
    }
    
    //Function to return the label's original background when the mouse exited.
    public void scaleimage__backc_white_remove(JLabel label) {
        ImageIcon icon = new ImageIcon("");
        Image img = icon.getImage();
        Image imgscale = img.getScaledInstance(label.getWidth(), label.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgscale);
        label.setIcon(scaledIcon);
    }

    //Function to replace the button with another one with a different color.
    public void scaleimage__replaceButton(JLabel label, String path) {
        ImageIcon icon = new ImageIcon(path);
        Image img = icon.getImage();
        Image imgscale = img.getScaledInstance(label.getWidth(), label.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgscale);
        label.setIcon(scaledIcon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLbl_returnBack = new javax.swing.JLabel();
        jLbl_UpBar = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLbl_viewGrades = new javax.swing.JLabel();
        jLbl_Evaluation = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(1283, 694));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 252, 239));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sprint#3Images/GradesIcon.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 70));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Grading System");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 8, 420, 60));

        jLbl_returnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sprint#3Images/OrangeExit.png"))); // NOI18N
        jLbl_returnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLbl_returnBackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLbl_returnBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLbl_returnBackMouseExited(evt);
            }
        });
        jPanel1.add(jLbl_returnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 10, 40, 40));

        jLbl_UpBar.setBackground(new java.awt.Color(38, 50, 54));
        jLbl_UpBar.setOpaque(true);
        jPanel1.add(jLbl_UpBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 70));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sprint#3Images/Grades.gif"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, 800, 630));

        jLbl_viewGrades.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLbl_viewGrades.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbl_viewGrades.setText("View Grades");
        jLbl_viewGrades.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(98, 168, 243)));
        jLbl_viewGrades.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLbl_viewGrades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLbl_viewGradesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLbl_viewGradesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLbl_viewGradesMouseExited(evt);
            }
        });
        jPanel1.add(jLbl_viewGrades, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 320, 50));

        jLbl_Evaluation.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLbl_Evaluation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbl_Evaluation.setText("Assign Assignment To TA");
        jLbl_Evaluation.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(98, 168, 243)));
        jLbl_Evaluation.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLbl_Evaluation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLbl_EvaluationMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLbl_EvaluationMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLbl_EvaluationMouseExited(evt);
            }
        });
        jPanel1.add(jLbl_Evaluation, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, 320, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLbl_returnBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbl_returnBackMouseExited
        scaleimage__replaceButton(jLbl_returnBack, "src\\photo\\botton\\OrangeExit.png");
    }//GEN-LAST:event_jLbl_returnBackMouseExited

    private void jLbl_returnBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbl_returnBackMouseEntered
        scaleimage__backcwhite(jLbl_returnBack, "src\\photo\\botton\\rel_exit.png");
    }//GEN-LAST:event_jLbl_returnBackMouseEntered
    
    //View Grade Specifications Interface when this button is clicked.
    private void jLbl_viewGradesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbl_viewGradesMouseClicked
        //Once this button is clicked, you must retrieve the grades of the selected
        //section, and fill it in the table.
        
        new CourseGradesProf().setVisible(true);
        dispose();
    }//GEN-LAST:event_jLbl_viewGradesMouseClicked

    private void jLbl_viewGradesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbl_viewGradesMouseEntered
        scaleimage__backcwhite(jLbl_viewGrades, "src\\photo\\white.png");
        jLbl_viewGrades.setForeground(new Color(98, 168, 243));
    }//GEN-LAST:event_jLbl_viewGradesMouseEntered

    private void jLbl_viewGradesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbl_viewGradesMouseExited
        scaleimage__backc_white_remove(jLbl_viewGrades);
        jLbl_viewGrades.setForeground(Color.black);
    }//GEN-LAST:event_jLbl_viewGradesMouseExited

    //View Assignments Evaluation Interface when this button is clicked.    
    private void jLbl_EvaluationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbl_EvaluationMouseClicked
        try {
            //Once this button is clicked, you must retrieve the TA details of the selected
            //section (if there is any), and fill its specified details in the labels, otherwise
            //display a notification that shows that this section of this course doesn't have TAs.

            DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
            String user,url,Password;
            url="jdbc:oracle:thin:@LAPTOP-1270LE9S:1521:XE";
            user="C##happygrades";
            Password="scranton";
            Connection con = DriverManager.getConnection(url,user,Password);
            con.setAutoCommit(false);
            String sql = "select teachers_sections.teacherid, teachers.teachername, teachers.email\n" +
                        "from teachers_sections, teachers\n" +
                        "where teachers_sections.sectionno = "+ProfessorCourseSections.sel_sec+"\n" +
                        "and teachers.teacherid = teachers_sections.teacherid\n" +
                        "and teachers.tmode = 'TA'" ;      
            Statement smt = con.createStatement();
            ResultSet ta  = smt.executeQuery(sql);
            while(ta.next()){
                new AssignmentsEvaluation(ta).setVisible(true);
            
                dispose();
                return;
            }
            callTimer(new ErrorNotification("No Teacher Assistant Found!"));
        } catch (SQLException ex) {
            Logger.getLogger(ProfessorGradingInterface.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLbl_EvaluationMouseClicked

    private void callTimer(JFrame notification) {
        Timer timer = new Timer();
        notification.setVisible(true);
        timer.schedule(new TimerTask() {
            @Override
            public void run() {
                notification.setVisible(false);
            }
        }, 6000);
    }
    private void jLbl_EvaluationMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbl_EvaluationMouseEntered
        scaleimage__backcwhite(jLbl_Evaluation, "src\\photo\\white.png");
        jLbl_Evaluation.setForeground(new Color(98, 168, 243));
    }//GEN-LAST:event_jLbl_EvaluationMouseEntered

    private void jLbl_EvaluationMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbl_EvaluationMouseExited
        scaleimage__backc_white_remove(jLbl_Evaluation);
        jLbl_Evaluation.setForeground(Color.black);
    }//GEN-LAST:event_jLbl_EvaluationMouseExited

    private void jLbl_returnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbl_returnBackMouseClicked
        try {
            // TODO add your handling code here:
            //You must determine the number of sections again for this Prof. to display the sections
            //page again when we click on return back, new ProfessorCourseSections(numOfSections)
            //.setVisible(true); or you could make a reference to the sections
            //page of this prof and use it each time. Feel free to do what you need!
            //this.setVisible(false);
            new ProfessorCourseSections(ProfessorCourseSections.secs.size()).setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(ProfessorGradingInterface.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
    }//GEN-LAST:event_jLbl_returnBackMouseClicked

   
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CourseGradesProf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CourseGradesProf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CourseGradesProf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CourseGradesProf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProfessorGradingInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLbl_Evaluation;
    private javax.swing.JLabel jLbl_UpBar;
    private javax.swing.JLabel jLbl_returnBack;
    private javax.swing.JLabel jLbl_viewGrades;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
