

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author User
 */
public class SuccessNotification extends javax.swing.JFrame {

    /**
     * Creates new form Notification
     */
    public SuccessNotification(String text) {
        initComponents();
        jLbl_Text.setText(text);
        this.setLocation(965, 570);
    }
    public SuccessNotification() {
        initComponents();
        this.setLocation(965, 570);
    }
    //function to set a text in the label of the notification.
    public void setText(String text) {
        jLbl_Text.setText(text);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLbl_header = new javax.swing.JLabel();
        jLbl_Text = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);

        jLbl_header.setBackground(new java.awt.Color(38, 50, 54));
        jLbl_header.setFont(new java.awt.Font("Edwardian Script ITC", 1, 30)); // NOI18N
        jLbl_header.setForeground(new java.awt.Color(255, 255, 255));
        jLbl_header.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbl_header.setText("Happy Grades ");
        jLbl_header.setOpaque(true);
        jPanel1.add(jLbl_header);
        jLbl_header.setBounds(0, 0, 320, 55);

        jLbl_Text.setBackground(new java.awt.Color(255, 255, 255));
        jLbl_Text.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLbl_Text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbl_Text.setOpaque(true);
        jPanel1.add(jLbl_Text);
        jLbl_Text.setBounds(0, 50, 320, 60);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SuccessNotification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SuccessNotification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SuccessNotification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SuccessNotification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SuccessNotification().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLbl_Text;
    private javax.swing.JLabel jLbl_header;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
