


import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.JTableHeader;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class TeacherGradingInterface extends javax.swing.JFrame {

    /**
     * Creates new form CourseGradesProf
     */
    public TeacherGradingInterface() {
        initComponents();
    }
    
    //General Notes
    //Once the TA selects one section from the the sections, a CourseGradesTA interface will be opened
    //and filled with students' assignments (1 & 2) grades of this selected section if TA
    //has access to the evaluation, otherwise, only the names & IDs will be viewd, so in this case,
    //you can make the buttons "add grade", "remove grade", "update grade" hidden,
    //while you can keep jTxt_StuID, jTxt_Grade (it's normally used to fill a grade but in this case for Student's name)
    //since the TA hasn't access to the evaluation process, he won't able to see grades, so use these
    //fields to display the student ID, and the student's name when the TA search for a specific student by ID.

    
    public TeacherGradingInterface(int CoursesOfProf) {
        initComponents();
    }
    
    //Function to make the label's background white when the mouse entered.
    public void scaleimage__backcwhite(JLabel label, String path) {
        ImageIcon icon = new ImageIcon(path);
        Image img = icon.getImage();
        Image imgscale = img.getScaledInstance(label.getWidth(), label.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgscale);
        label.setIcon(scaledIcon);
    }
    
    //Function to return the label's original background when the mouse exited.
    public void scaleimage__backc_white_remove(JLabel label) {
        ImageIcon icon = new ImageIcon("");
        Image img = icon.getImage();
        Image imgscale = img.getScaledInstance(label.getWidth(), label.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgscale);
        label.setIcon(scaledIcon);
    }
    
    //Function to replace the button with another one with a different color.
    public void scaleimage__replaceButton(JLabel label, String path) {
        ImageIcon icon = new ImageIcon(path);
        Image img = icon.getImage();
        Image imgscale = img.getScaledInstance(label.getWidth(), label.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgscale);
        label.setIcon(scaledIcon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLbl_returnBack = new javax.swing.JLabel();
        jLbl_UpBar = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLbl_Assignment1 = new javax.swing.JLabel();
        jLbl_Assignment2 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(1283, 694));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 252, 239));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sprint#3Images/GradesIcon.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 70));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Grading System");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 8, 420, 60));

        jLbl_returnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sprint#3Images/OrangeExit.png"))); // NOI18N
        jLbl_returnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLbl_returnBackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLbl_returnBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLbl_returnBackMouseExited(evt);
            }
        });
        jPanel1.add(jLbl_returnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 10, 40, -1));

        jLbl_UpBar.setBackground(new java.awt.Color(38, 50, 54));
        jLbl_UpBar.setOpaque(true);
        jPanel1.add(jLbl_UpBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 70));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sprint#3Images/Grades.gif"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, 800, 630));

        jLbl_Assignment1.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLbl_Assignment1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbl_Assignment1.setText("Evaluate Assignment1 ");
        jLbl_Assignment1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(98, 168, 243)));
        jLbl_Assignment1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLbl_Assignment1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLbl_Assignment1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLbl_Assignment1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLbl_Assignment1MouseExited(evt);
            }
        });
        jPanel1.add(jLbl_Assignment1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 320, 50));

        jLbl_Assignment2.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLbl_Assignment2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbl_Assignment2.setText("Evaluate Assignment2");
        jLbl_Assignment2.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(98, 168, 243)));
        jLbl_Assignment2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLbl_Assignment2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLbl_Assignment2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLbl_Assignment2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLbl_Assignment2MouseExited(evt);
            }
        });
        jPanel1.add(jLbl_Assignment2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, 320, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLbl_returnBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbl_returnBackMouseExited
        scaleimage__replaceButton(jLbl_returnBack, "src\\photo\\botton\\OrangeExit.png");
    }//GEN-LAST:event_jLbl_returnBackMouseExited

    private void jLbl_returnBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbl_returnBackMouseEntered
        scaleimage__backcwhite(jLbl_returnBack, "src\\photo\\botton\\rel_exit.png");
    }//GEN-LAST:event_jLbl_returnBackMouseEntered

    private void jLbl_returnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbl_returnBackMouseClicked
        //You must determine the number of sections again for this TA to display the sections
        //page again when we click on return back, new TACourseSections(numOfSections)
        //.setVisible(true); or you could make a reference to the sections
        //page of this TA and use it each time. Feel free to do what you need!
        //this.setVisible(false);
        
    }//GEN-LAST:event_jLbl_returnBackMouseClicked

    private void jLbl_Assignment1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbl_Assignment1MouseClicked
        //Once this button is clicked, you must retrieve the grades
        //of the selected section for assignment1, and fill it in the table (if there is any).
        //a new grading interface "CourseGrades1TA" will be displayed.
    }//GEN-LAST:event_jLbl_Assignment1MouseClicked

    private void jLbl_Assignment1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbl_Assignment1MouseEntered
        scaleimage__backcwhite(jLbl_Assignment1, "src\\photo\\white.png");
        jLbl_Assignment1.setForeground(new Color(98, 168, 243));
    }//GEN-LAST:event_jLbl_Assignment1MouseEntered

    private void jLbl_Assignment1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbl_Assignment1MouseExited
        scaleimage__backc_white_remove(jLbl_Assignment1);
        jLbl_Assignment1.setForeground(Color.black);
    }//GEN-LAST:event_jLbl_Assignment1MouseExited

    private void jLbl_Assignment2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbl_Assignment2MouseClicked
        //Once this button is clicked, you must retrieve the grades
        //of the selected section for assignment2, and fill it in the table (if there is any).
        //a new grading interface "CourseGrades2TA" will be displayed.
    }//GEN-LAST:event_jLbl_Assignment2MouseClicked

    private void jLbl_Assignment2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbl_Assignment2MouseEntered
        scaleimage__backcwhite(jLbl_Assignment2, "src\\photo\\white.png");
        jLbl_Assignment2.setForeground(new Color(98, 168, 243));
    }//GEN-LAST:event_jLbl_Assignment2MouseEntered

    private void jLbl_Assignment2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbl_Assignment2MouseExited
        scaleimage__backc_white_remove(jLbl_Assignment2);
        jLbl_Assignment2.setForeground(Color.black);
    }//GEN-LAST:event_jLbl_Assignment2MouseExited

   
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CourseGradesProf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CourseGradesProf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CourseGradesProf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CourseGradesProf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TeacherGradingInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLbl_Assignment1;
    private javax.swing.JLabel jLbl_Assignment2;
    private javax.swing.JLabel jLbl_UpBar;
    private javax.swing.JLabel jLbl_returnBack;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
